DATA_DIR = "data"
RAW_FILENAME = "foodbanks.csv"

# OD matrix building
FOODBANK_FILENAME = "foodbank_coords.csv"
POSTCODE_FILENAME = "shef_pc_coords_lookup.csv"
OD_FILENAME = "foodbank_postcode_od.csv"
